name: pencraftpro
description: "PenCraft Pro is the perfect digital notebook for students, designed to make note-taking and sketching effortless. Whether you're jotting down lecture notes, creating mind maps, or organizing ideas, PenCraft Pro keeps it simple and intuitive—just like writing on paper. Enjoy an easy-to-use platform with essential features for organizing, saving, and accessing your notes anytime, anywhere. Perfect for beginners, PenCraft Pro helps students focus on learning without the complications."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 2.0.0+2

environment:
  sdk: ^3.7.2

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.5.2
  google_sign_in: ^6.3.0
  shared_preferences: ^2.5.3
  firebase_core: ^3.13.0
  flutter_svg: ^2.1.0
  url_launcher: ^6.3.1
  email_validator: ^3.0.0
  cloud_firestore: ^5.6.6
  flutter_staggered_grid_view: ^0.7.0
  provider: ^6.1.4
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  record: ^6.0.0
  path_provider: ^2.1.5
  flutter_local_notifications: ^19.1.0
  permission_handler: ^12.0.0+1
  uuid: ^4.5.1
  timezone: ^0.10.0
  zefyrka: ^1.6.0
  notus: ^1.0.0-rc.2
  flutter_quill: ^11.4.0
  device_info_plus: ^11.4.0
  flutter_markdown: ^0.7.7
  just_audio: ^0.10.1
  pdf: ^3.11.3
  printing: ^5.14.2
  firebase_storage: ^12.4.5
  flutter_colorpicker: ^1.1.0
  image: ^4.2.0
  flutter_image_gallery_saver: ^0.0.2
  flutter_screenutil: ^5.9.3
  connectivity_plus: ^6.1.4

  flutter_localizations:
    sdk: flutter
  easy_localization: ^3.0.7+1
  audioplayers: ^6.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo.png
    - assets/logo1.png
    - assets/icon.png
    - assets/aclc.png
    - assets/google_logo.svg
    - assets/fonts/Roboto-Regular.ttf
    - assets/fonts/TimesNewRoman-Regular.ttf
    - assets/fonts/courier-normal.ttf
    - assets/fonts/DancingScript-Regular.ttf
    - assets/fonts/Pacifico-Regular.ttf
    - assets/fonts/SpaceMono-Regular.ttf
    - assets/fonts/GreatVibes-Regular.ttf
    - assets/fonts/ShadowsIntoLight-Regular.ttf
    - assets/fonts/GloriaHallelujah-Regular.ttf
    - assets/fonts/IndieFlower-Regular.ttf
    - assets/fonts/Satisfy-Regular.ttf
    - assets/fonts/HomemadeApple-Regular.ttf
    - assets/fonts/ReenieBeanie-Regular.ttf
    - assets/fonts/Handlee-Regular.ttf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: Times New Roman # Add if you have the file
      fonts:
        - asset: assets/fonts/TimesNewRoman-Regular.ttf
    - family: Courier New
      fonts:
        - asset: assets/fonts/courier-normal.ttf
    - family: Dancing Script
      fonts:
        - asset: assets/fonts/DancingScript-Regular.ttf
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
    - family: Space Mono
      fonts:
        - asset: assets/fonts/SpaceMono-Regular.ttf
    - family: Great Vibes
      fonts:
        - asset: assets/fonts/GreatVibes-Regular.ttf
    - family: Shadows Into Light
      fonts:
        - asset: assets/fonts/ShadowsIntoLight-Regular.ttf
    - family: Gloria Hallelujah
      fonts:
        - asset: assets/fonts/GloriaHallelujah-Regular.ttf
    - family: Indie Flower
      fonts:
        - asset: assets/fonts/IndieFlower-Regular.ttf
    - family: Satisfy
      fonts:
        - asset: assets/fonts/Satisfy-Regular.ttf
    - family: Homemade Apple
      fonts:
        - asset: assets/fonts/HomemadeApple-Regular.ttf
    - family: Reenie Beanie
      fonts:
        - asset: assets/fonts/ReenieBeanie-Regular.ttf
    - family: Handlee
      fonts:
        - asset: assets/fonts/Handlee-Regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
